require("jade.set")
-- load remap first as it defines the leader key
require("jade.remap")

require("jade.lazynvim")
require("jade.lsp")
require("jade.lazypush")
require("jade.colorscheme")
require("jade.filetype")
require("jade.localopen")
require("jade.ji")
require("jade.treesitter")
require("jade.format")
require("jade.diagnostics")
require("jade.refresh")
require("jade.neovide")
require("jade.pages")
require("jade.repl")
